# Generated by Django 3.1.2 on 2020-10-08 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Covoiturage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('Conducteur', 'Conducteur'), ('Passager', 'Passager')], max_length=200, verbose_name='Vous êtes ?')),
                ('start_destination', models.CharField(max_length=200, verbose_name='Adresse de départ')),
                ('end_destination', models.CharField(max_length=200, verbose_name="Adresse d'arrivée")),
                ('date_depart', models.DateField(verbose_name='Date de départ')),
                ('time_depart', models.TimeField(verbose_name='Heure de départ')),
                ('siege', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=200, verbose_name='Nombre de place disponible')),
                ('price', models.PositiveIntegerField(verbose_name='Prix par passager')),
                ('voiture', models.CharField(blank=True, choices=[('Citadine', 'Citadine'), ('4x4', '4x4'), ('Taxi', 'Taxi'), ('Monospace', 'Monospace'), ('Coupé', 'Coupé'), ('Berline', 'Berline'), ('Minibus', 'Minibus'), ('Bus', 'Bus'), ('Car', 'Car'), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Type de voiture')),
                ('bagage', models.CharField(choices=[('Pas de bagage', 'Pas de bagage'), ('Petit Sac', 'Petit Sac'), ('1 Valise', '1 Valise'), ('2 Valises', '2 Valises'), ('3 Valises', '3 Valises'), ('4 Valises', '4 Valises'), ('Beaucoup de Bagages', 'Beaucoup de Bagages')], max_length=200, verbose_name='Type de Bagage')),
                ('smoking', models.BooleanField(default=False, verbose_name='Êtes-vous un fumeur ?')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Information sur votre trajet')),
                ('certificated', models.BooleanField(default=False)),
                ('activated', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
